# Generated by Django 3.0.8 on 2020-09-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200905_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='bookmark',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
